language: python

python:
  - "2.7"

install:
  - pip install -r requirements.txt --use-mirrors

script:
  - mkdir ./tmp
  - mv ./settings_for_travis.py ./stucampus/settings.py
  - python ./manage.py test

branches:
  only:
    - develop
